### ISSUE TITLE
log out function of config-ui does not word

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DirectProject/nhin-d#250]
```
What steps will reproduce the problem?
1. login to config-ui as admin
2. press log out button

What is the expected output? What do you see instead?
excepted result: log out successfully
test result: return an error page.

What version of the product are you using? On what operating system?
config-ui 1.3 linux or mac os

Please provide any additional information below.


```

Original issue reported on code.google.com by `xudingdi...@gmail.com` on 10 Dec 2014 at 9:24

Attachments:
* [Screen Shot 2014-12-11 at 10.23.51 am.png](https://storage.googleapis.com/google-code-attachments/nhin-d/issue-250/comment-0/Screen Shot 2014-12-11 at 10.23.51 am.png)

**Comment by gm2552** [comment]
The Direct RI version 5.1 (currently in Beta) includes some new functionality, but is going to be deprecated and replaced with a complete rewrite.  The current version is very difficult to maintain, hard to add new functionality, and the original coders are no longer with the project.  We are looking into writing the new version as single page browser app written in AngularJS.
